### ISSUE TITLE
关于触发方式，视觉模式的疑惑

### ISSUE THREAD

**Issue by HUSTerAIA** [ElvisChenML/Waifu#1]
作者的项目非常nice。但存在以下疑惑：
![图片](https://github.com/ElvisChenML/Waifu/assets/76442163/bcb32bd0-55f1-4031-9e0b-7c3f76681c7f)
如图启用群聊模式之后，原项目的其他对话触发方式（at对话、前缀模式、正则表达式等）好像失效了？
![图片](https://github.com/ElvisChenML/Waifu/assets/76442163/11d30a78-c3c0-4a78-82d1-28ce8f1b51ad)
此外使用包含视觉能力的模型（如gpt-4o等）好像并没有识别图片信息的效果？

此外使用命令列表中的指令（例如[列出命令]）貌似不起作用？
感谢作者！

**Comment by ElvisChenML** [comment]
1. 触发方式：因为主项目random设置为1时其他就不会有作用了，但插件如果要接管回复时机就需要主项目设置成全触发（random：1），不然插件会直到触发主项目回复规则后才收到群组事件。除了@的其他触发方式我可以读取配置文件继承过来自己实现，但@目前还不行，我提了个issue给主项目，@消息目前无法在事件中获取。
2. 关于图片目前还不行，这个我会在后续版本添加上。

**Comment by HUSTerAIA** [comment]
> 1. 触发方式：因为主项目random设置为1时其他就不会有作用了，但插件如果要接管回复时机就需要主项目设置成全触发（random：1），不然插件会直到触发主项目回复规则后才收到群组事件。除了@的其他触发方式我可以读取配置文件继承过来自己实现，但@目前还不行，我提了个issue给主项目，@消息目前无法在事件中获取。
> 
>     2. 关于图片目前还不行，这个我会在后续版本添加上。

感谢作者回复，另外插件命令好像不起作用，还是说我的使用方式不对：
![图片](https://github.com/ElvisChenML/Waifu/assets/76442163/684be257-6869-4aa8-a89e-7a726a79834f)

**Comment by ElvisChenML** [comment]
<img width="658" alt="image" src="https://github.com/ElvisChenML/Waifu/assets/42546145/efaadb0d-554c-44b3-be8c-40e924b75346">
命令使用参考Usage Example，不需要[]

**Comment by HUSTerAIA** [comment]
> <img alt="image" width="658" src="https://private-user-images.githubusercontent.com/42546145/346309252-efaadb0d-554c-44b3-be8c-40e924b75346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjI2NTUsIm5iZiI6MTcyMDMyMjM1NSwicGF0aCI6Ii80MjU0NjE0NS8zNDYzMDkyNTItZWZhYWRiMGQtNTU0Yy00NGIzLWJlOGMtNDBlOTI0Yjc1MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAzMTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMzljYjdjNjcxYzlhM2ZlZjllYWRhMGI3ZmI1NjgzODBhYzkwZjgzN2Q5MjQ1NTczMTlmZTZiYzRjNzY3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nq9kvRerRpf2-2wNB5pdLffblkFntpsapXAK62Gf5B4"> 命令使用参考Usage Example，不需要[]

明白了，感谢
