### ISSUE TITLE
请设计命令报错;开场场景文本缺失

### ISSUE THREAD

**Issue by normana234** [ElvisChenML/Waifu#10]
1、后台显示如图，前台无回复
![捕获](https://github.com/user-attachments/assets/1d0d07fd-ad5c-4051-b671-5aef5dbe1b0f)

2、用的默认预设，后台没看到对应文本，询问gpt让我在cards.py里添加一行
    def _collect_prompt_sections(self) -> typing.List[typing.Tuple[str, typing.Any]]:
        sections = [
            ("Profile", self._profile),
            ("Skills", self._skills),
            ("Background", self._background),
            ("Memories", self._memories),
            ("Rules", self.get_rules()),
# 添加
            ("Prologue", [self.get_prologue()]) 
好像有用(完全代码外行，不确定)

3、jail_break_mode: "end" # off/before/after/end；这个配置能不能设计成可多选(off外)，部分情况前置后置和end要一起用效果更好

**Comment by ElvisChenML** [comment]
1. 我再帮你确认。
2. 设计这个功能是需要手动触发而不是每次都附在提示语里，请输入命令：开场场景。
3. 我考虑看看怎么加，议题先帮你留着。

**Comment by normana234** [comment]
@ElvisChenML 知道了，谢谢
