### ISSUE TITLE
1.92报错

### ISSUE THREAD

**Issue by normana234** [ElvisChenML/Waifu#13]
截图如下(看不懂)
![error](https://github.com/user-attachments/assets/3030f294-8c65-43d1-90d9-06ae09fee3c6)
用命令更新后出现报错，于是从langbot开始重新部署了一遍。
未装waifu插件时正常回复。安装后发送消息即出现报错，插件未修改任何配置保持默认。

**Comment by ElvisChenML** [comment]
主项目接口变动，已于 511e542 修复。
