### ISSUE TITLE
【bug】使用插件后，不能及时回复，并且整合消息回复时，不会发到群聊

### ISSUE THREAD

**Issue by ShanJianSoda** [ElvisChenML/Waifu#2]
![image](https://github.com/ElvisChenML/Waifu/assets/128208553/06caec25-73f3-477c-b458-cb2fd38c7c40)
命令行里有response，但是qq群里没有发出

环境：
和项目一致

windows11

**Comment by ElvisChenML** [comment]
不能及时回复请确认是否由这个参数的设定影响，可以尝试缩短消息合并等待时间。
person_response_delay: 5 # 私聊消息合并等待时间
group_response_delay: 10 # 群聊消息合并等待时间

图中的心理活动如果要发到QQ中需要开启选项：
display_thinking: true # 是否显示内心活动。

如果有疑问，可以提供日志以及QQ截图进一步反馈。
