### ISSUE TITLE
严重的报错，是api的问题还是此插件的问题？

### ISSUE THREAD

**Issue by yizhitian1145** [ElvisChenML/Waifu#3]
你好，我在使用waifu插件时遇到了以下的报错，第一次报错是这个
![14a96ee2916bdeef9f8045efb52feeaf](https://github.com/user-attachments/assets/fb8ef1ee-16c0-4a12-84b4-c9efef405f11)

开始我还以为时api的模型错了，就换了个，结果出了这一坨报错
![8fc10af92547e78699906c790a5d0373](https://github.com/user-attachments/assets/1c0e9aae-8af2-4f9f-bd87-1a8e72a02e1e)
![b76413b99b58675ed1f37c77a31b52d5](https://github.com/user-attachments/assets/7abf34ba-ad6b-4dbc-983e-82d88ca69a6d)
这两个截图没有截完
所以不知道是我这个中转站的api问题还是插件哪里有问题？
如果不是插件问题我尝试自己改下配置，如果确实有这问题，请插件大大修复一下。

linux服务器系统为Ubuntu-22.04-x64
qchatgpt和插件都更新了

**Comment by ElvisChenML** [comment]
需要提供未启用插件的消息截图，请在私聊画面执行主项目命令 !plugin off Waifu，然后发消息看看是否正常。

**Comment by yizhitian1145** [comment]
> 需要提供未启用插件的消息截图，请在私聊画面执行主项目命令 ！plugin off Waifu，然后发消息看看是否正常。

好的，是apI中转站的问题，抱歉打扰你了。
