### ISSUE TITLE
关于破除限制提示语的位置

### ISSUE THREAD

**Issue by normana234** [ElvisChenML/Waifu#6]
看后台显示，文本顺序是前置破限，角色信息，后置破限，对话内容。
能不能把后置破限放对话内容后面，或者加个设置项，选择放置的位置。
破限的效力在文本最下方效果最好，没有破限需求也能用来固定一些格式。
放在对话上面，当对话内容过长容易失效。
(叠个甲，看不懂代码，只能看后台判断文本顺序了)

**Comment by ElvisChenML** [comment]
已于 1d7f946 实现，关闭此议题。
